package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

/*GetKeysKeyOK Successful response

swagger:response getKeysKeyOK
*/
type GetKeysKeyOK struct {
}

// NewGetKeysKeyOK creates GetKeysKeyOK with default headers values
func NewGetKeysKeyOK() *GetKeysKeyOK {
	return &GetKeysKeyOK{}
}

// WriteResponse to the client
func (o *GetKeysKeyOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
}

/*GetKeysKeyNotFound Not found.

swagger:response getKeysKeyNotFound
*/
type GetKeysKeyNotFound struct {
}

// NewGetKeysKeyNotFound creates GetKeysKeyNotFound with default headers values
func NewGetKeysKeyNotFound() *GetKeysKeyNotFound {
	return &GetKeysKeyNotFound{}
}

// WriteResponse to the client
func (o *GetKeysKeyNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}
