package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

/*PostKeysKeyOK Successful response

swagger:response postKeysKeyOK
*/
type PostKeysKeyOK struct {
}

// NewPostKeysKeyOK creates PostKeysKeyOK with default headers values
func NewPostKeysKeyOK() *PostKeysKeyOK {
	return &PostKeysKeyOK{}
}

// WriteResponse to the client
func (o *PostKeysKeyOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
}
