package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import "encoding/json"

// SwaggerJSON embedded version of the swagger document used at generation time
var SwaggerJSON json.RawMessage

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Testman",
    "version": "0.0.0"
  },
  "host": "localhost",
  "basePath": "/api/v1",
  "paths": {
    "/keys/{key}": {
      "get": {
        "parameters": [
          {
            "type": "string",
            "name": "key",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response"
          },
          "404": {
            "description": "Not found."
          }
        }
      },
      "post": {
        "parameters": [
          {
            "type": "string",
            "name": "key",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "name": "value",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    }
  },
  "definitions": null
}`))
}
