package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetKeysKeyParams creates a new GetKeysKeyParams object
// with the default values initialized.
func NewGetKeysKeyParams() *GetKeysKeyParams {
	var ()
	return &GetKeysKeyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetKeysKeyParamsWithTimeout creates a new GetKeysKeyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetKeysKeyParamsWithTimeout(timeout time.Duration) *GetKeysKeyParams {
	var ()
	return &GetKeysKeyParams{

		timeout: timeout,
	}
}

// NewGetKeysKeyParamsWithContext creates a new GetKeysKeyParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetKeysKeyParamsWithContext(ctx context.Context) *GetKeysKeyParams {
	var ()
	return &GetKeysKeyParams{

		Context: ctx,
	}
}

// NewGetKeysKeyParamsWithHTTPClient creates a new GetKeysKeyParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetKeysKeyParamsWithHTTPClient(client *http.Client) *GetKeysKeyParams {
	var ()
	return &GetKeysKeyParams{
		HTTPClient: client,
	}
}

/*GetKeysKeyParams contains all the parameters to send to the API endpoint
for the get keys key operation typically these are written to a http.Request
*/
type GetKeysKeyParams struct {

	/*Key*/
	Key string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get keys key params
func (o *GetKeysKeyParams) WithTimeout(timeout time.Duration) *GetKeysKeyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get keys key params
func (o *GetKeysKeyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get keys key params
func (o *GetKeysKeyParams) WithContext(ctx context.Context) *GetKeysKeyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get keys key params
func (o *GetKeysKeyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get keys key params
func (o *GetKeysKeyParams) WithHTTPClient(client *http.Client) *GetKeysKeyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get keys key params
func (o *GetKeysKeyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithKey adds the key to the get keys key params
func (o *GetKeysKeyParams) WithKey(key string) *GetKeysKeyParams {
	o.SetKey(key)
	return o
}

// SetKey adds the key to the get keys key params
func (o *GetKeysKeyParams) SetKey(key string) {
	o.Key = key
}

// WriteToRequest writes these params to a swagger request
func (o *GetKeysKeyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param key
	if err := r.SetPathParam("key", o.Key); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
