package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PostKeysKeyReader is a Reader for the PostKeysKey structure.
type PostKeysKeyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostKeysKeyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostKeysKeyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostKeysKeyOK creates a PostKeysKeyOK with default headers values
func NewPostKeysKeyOK() *PostKeysKeyOK {
	return &PostKeysKeyOK{}
}

/*PostKeysKeyOK handles this case with default header values.

Successful response
*/
type PostKeysKeyOK struct {
}

func (o *PostKeysKeyOK) Error() string {
	return fmt.Sprintf("[POST /keys/{key}][%d] postKeysKeyOK ", 200)
}

func (o *PostKeysKeyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
