package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostKeysKeyParams creates a new PostKeysKeyParams object
// with the default values initialized.
func NewPostKeysKeyParams() *PostKeysKeyParams {
	var ()
	return &PostKeysKeyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostKeysKeyParamsWithTimeout creates a new PostKeysKeyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostKeysKeyParamsWithTimeout(timeout time.Duration) *PostKeysKeyParams {
	var ()
	return &PostKeysKeyParams{

		timeout: timeout,
	}
}

// NewPostKeysKeyParamsWithContext creates a new PostKeysKeyParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostKeysKeyParamsWithContext(ctx context.Context) *PostKeysKeyParams {
	var ()
	return &PostKeysKeyParams{

		Context: ctx,
	}
}

// NewPostKeysKeyParamsWithHTTPClient creates a new PostKeysKeyParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostKeysKeyParamsWithHTTPClient(client *http.Client) *PostKeysKeyParams {
	var ()
	return &PostKeysKeyParams{
		HTTPClient: client,
	}
}

/*PostKeysKeyParams contains all the parameters to send to the API endpoint
for the post keys key operation typically these are written to a http.Request
*/
type PostKeysKeyParams struct {

	/*Key*/
	Key string
	/*Value*/
	Value string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post keys key params
func (o *PostKeysKeyParams) WithTimeout(timeout time.Duration) *PostKeysKeyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post keys key params
func (o *PostKeysKeyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post keys key params
func (o *PostKeysKeyParams) WithContext(ctx context.Context) *PostKeysKeyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post keys key params
func (o *PostKeysKeyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post keys key params
func (o *PostKeysKeyParams) WithHTTPClient(client *http.Client) *PostKeysKeyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post keys key params
func (o *PostKeysKeyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithKey adds the key to the post keys key params
func (o *PostKeysKeyParams) WithKey(key string) *PostKeysKeyParams {
	o.SetKey(key)
	return o
}

// SetKey adds the key to the post keys key params
func (o *PostKeysKeyParams) SetKey(key string) {
	o.Key = key
}

// WithValue adds the value to the post keys key params
func (o *PostKeysKeyParams) WithValue(value string) *PostKeysKeyParams {
	o.SetValue(value)
	return o
}

// SetValue adds the value to the post keys key params
func (o *PostKeysKeyParams) SetValue(value string) {
	o.Value = value
}

// WriteToRequest writes these params to a swagger request
func (o *PostKeysKeyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param key
	if err := r.SetPathParam("key", o.Key); err != nil {
		return err
	}

	// query param value
	qrValue := o.Value
	qValue := qrValue
	if qValue != "" {
		if err := r.SetQueryParam("value", qValue); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
